"""add_memory_links_table

Revision ID: 0317f82c2c0b
Revises: f275a098249d
Create Date: 2026-08-29 01:02:30.711799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0317f82c2c0b'
down_revision: Union[str, Sequence[str], None] = 'f275a098249d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('source_memory_id', sa.Uuid(), nullable=False),
    sa.Column('target_memory_id', sa.Uuid(), nullable=False),
    sa.Column('link_type', sa.Enum('SHARED_ENTITY', 'SAME_SCENARIO', 'SEMANTIC_SIMILARITY', 'RELATED_INCIDENT', name='memorylinktype'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_memory_links_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_memory_id'], ['memory_entries.id'], name=op.f('fk_memory_links_source_memory_id_memory_entries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_memory_id'], ['memory_entries.id'], name=op.f('fk_memory_links_target_memory_id_memory_entries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_links')),
    sa.UniqueConstraint('organization_id', 'source_memory_id', 'target_memory_id', 'link_type', name='uq_memory_links_org_src_tgt_type')
    )
    op.create_index('ix_memory_links_organization_id', 'memory_links', ['organization_id'], unique=False)
    op.create_index('ix_memory_links_source_memory_id', 'memory_links', ['source_memory_id'], unique=False)
    op.create_index('ix_memory_links_target_memory_id', 'memory_links', ['target_memory_id'], unique=False)
    # NOTE: ix_memory_entries_embedding_hnsw is managed by migration 581c2cdd5ce2
    #       via raw SQL — excluded from autogenerate in alembic/env.py.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_memory_links_target_memory_id', table_name='memory_links')
    op.drop_index('ix_memory_links_source_memory_id', table_name='memory_links')
    op.drop_index('ix_memory_links_organization_id', table_name='memory_links')
    op.drop_table('memory_links')
    # ### end Alembic commands ###
