"""add_entities_and_memory_entities_tables

Revision ID: 54199dae8911
Revises: 581c2cdd5ce2
Create Date: 2026-08-27 23:32:32.021815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54199dae8911'
down_revision: Union[str, Sequence[str], None] = '581c2cdd5ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.Enum('PERSON', 'REPOSITORY', 'FILE', 'SERVICE', 'TECHNOLOGY', 'INCIDENT', 'PULL_REQUEST', 'BRANCH', 'API_ENDPOINT', name='entitytype'), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_entities_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities')),
    sa.UniqueConstraint('organization_id', 'entity_type', 'name', name='uq_entities_org_type_name')
    )
    op.create_index('ix_entities_entity_type', 'entities', ['entity_type'], unique=False)
    op.create_index('ix_entities_organization_id', 'entities', ['organization_id'], unique=False)
    op.create_table('memory_entities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('memory_entry_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_memory_entities_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['memory_entry_id'], ['memory_entries.id'], name=op.f('fk_memory_entities_memory_entry_id_memory_entries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_entities')),
    sa.UniqueConstraint('memory_entry_id', 'entity_id', name='uq_memory_entities_entry_entity')
    )
    # NOTE: ix_memory_entries_embedding_hnsw is managed by migration 581c2cdd5ce2
    #       via raw SQL — do not touch it here.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memory_entities')
    op.drop_index('ix_entities_organization_id', table_name='entities')
    op.drop_index('ix_entities_entity_type', table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
