"""add_entity_relationships_table

Revision ID: f275a098249d
Revises: 54199dae8911
Create Date: 2026-08-28 00:05:56.788856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f275a098249d'
down_revision: Union[str, Sequence[str], None] = '54199dae8911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_relationships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('source_entity_id', sa.Uuid(), nullable=False),
    sa.Column('target_entity_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.Enum('REFERENCES', 'IMPLEMENTS', 'FIXES', 'DEPENDS_ON', 'REVIEWED_BY', 'RELATED_TO', 'CAUSED_BY', name='relationshiptype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_entity_relationships_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], name=op.f('fk_entity_relationships_source_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], name=op.f('fk_entity_relationships_target_entity_id_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_relationships')),
    sa.UniqueConstraint('organization_id', 'source_entity_id', 'target_entity_id', 'relationship_type', name='uq_entity_relationships_org_src_tgt_type')
    )
    op.create_index('ix_entity_relationships_organization_id', 'entity_relationships', ['organization_id'], unique=False)
    op.create_index('ix_entity_relationships_source_entity_id', 'entity_relationships', ['source_entity_id'], unique=False)
    op.create_index('ix_entity_relationships_target_entity_id', 'entity_relationships', ['target_entity_id'], unique=False)
    # NOTE: ix_memory_entries_embedding_hnsw is managed by migration 581c2cdd5ce2
    #       via raw SQL — do not touch it here.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entity_relationships_target_entity_id', table_name='entity_relationships')
    op.drop_index('ix_entity_relationships_source_entity_id', table_name='entity_relationships')
    op.drop_index('ix_entity_relationships_organization_id', table_name='entity_relationships')
    op.drop_table('entity_relationships')
    # ### end Alembic commands ###
